/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a33e6f8b-d9a2-48f3-909b-08ee2fcc61a3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_OdmcU0KOl",
    "aws_user_pools_web_client_id": "7lf4fdiolb5a7sm845np4num9u",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://vuafu6bbl5f7jcc7hfkzlou52e.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-eahtcstrsjgudjzqzmgr3p4ct4",
    "aws_user_files_s3_bucket": "valimage192606-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
